@startuml
node github://marialoni/site
node github://marialoni/marialoni.github.io
node https://www.marialoni.org

github://marialoni/site -> github://marialoni/marialoni.github.io
github://marialoni/marialoni.github.io -> node https://www.marialoni.org
@enduml
